dist: trusty
sudo: false
language: cpp

install:
  - sudo apt-get install -qq libboost-system1.54-dev
  - sudo apt-get install -qq libboost-filesystem1.54-dev
  - sudo apt-get install -qq libboost-thread1.54-dev
  - sudo apt-get install -qq libboost-chrono1.54-dev
  - sudo apt-get install -qq libboost-regex1.54-dev

script:
  - mkdir -p build-11
  - cd build-11
  - cmake -DCMAKE_CXX_STANDARD=11 -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . && ctest


notifications:
  email: true