dist: trusty
sudo: true
language: cpp
compiler:
    - gcc

before_install:
    - sudo apt-get install -qq libboost1.54-dev
    - sudo apt-get install -qq libboost-system1.54-dev
    - sudo apt-get install -qq libboost-filesystem1.54-dev
    - sudo apt-get install -qq libboost-thread1.54-dev
    - sudo apt-get install -qq libboost-chrono1.54-dev
    - sudo apt-get install -qq libboost-regex1.54-dev

env:
    - CXX_STANDARD=98
    - CXX_STANDARD=11

script: ./build_and_test.sh

notifications:
  email: false
