dist: trusty
sudo: false
language: cpp
compiler:
  - gcc
  - clang

install:
  - sudo apt-get install -qq libboost-system1.54-dev
  - sudo apt-get install -qq libboost-filesystem1.54-dev
  - sudo apt-get install -qq libboost-thread1.54-dev
  - sudo apt-get install -qq libboost-chrono1.54-dev
  - sudo apt-get install -qq libboost-regex1.54-dev

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - g++-4.8
      env:
        - CXX_STANDARD=98

script: travis-build.sh

notifications:
  email: true
