#define HAVE_PTHREAD 1

#define HAVE_BOOST_CHRONO 1

#define HAVE_BOOST_FILESYSTEM 1

#define HAVE_BOOST_RATIO 1

#define HAVE_BOOST_REGEX 1

#define HAVE_BOOST_SMART_PTR 1

#define HAVE_BOOST_SYSTEM_ERROR 1

#define HAVE_BOOST_THREAD 1

